In [1]:
import pandas as pd

In [2]:
climate = pd.read_csv(
    "../data/processed/climate_western_ghats_2015_2024.csv"
)

ndvi = pd.read_csv(
    "../data/processed/ndvi_western_ghats_2015_2024.csv"
)

forest = pd.read_csv(
    "../data/processed/forest_loss_western_ghats.csv"
)

elevation = pd.read_csv(
    "../data/processed/elevation_western_ghats.csv"
)
print("Datasets Loaded.")

Datasets Loaded.

In [3]:
datasets = {
    "Climate": climate,
    "NDVI": ndvi,
    "Forest": forest,
    "Elevation": elevation
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)

    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicates:", df.duplicated().sum())

    print()

============================================================
Climate
============================================================
Shape: (78, 9)

Columns:
['State', 'District', 'Year', 'Temperature', 'Min_Temperature', 'Max_Temperature', 'Rainfall', 'wspd', 'pres']

Missing Values:
State               0
District            0
Year                0
Temperature         0
Min_Temperature     0
Max_Temperature     0
Rainfall            0
wspd               24
pres               34
dtype: int64

Duplicates: 0

============================================================
NDVI
============================================================
Shape: (90, 4)

Columns:
['State', 'District', 'Year', 'NDVI']

Missing Values:
State       0
District    0
Year        0
NDVI        0
dtype: int64

Duplicates: 0

============================================================
Forest
============================================================
Shape: (9, 3)

Columns:
['State', 'District', 'Forest_Loss']

Missing Values:
State          0
District       0
Forest_Loss    0
dtype: int64

Duplicates: 0

============================================================
Elevation
============================================================
Shape: (9, 3)

Columns:
['State', 'District', 'Elevation']

Missing Values:
State        0
District     0
Elevation    0
dtype: int64

Duplicates: 0

In [4]:
master = climate.merge(
    forest,
    on=["State", "District"],
    how="left"
)

print(master.shape)
master.head()

(78, 10)

,State,District,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss
0,Karnataka,Shivamogga,2021,24.506868,13.2,37.2,1779.7,8.926923,1010.807967,0.019144
1,Karnataka,Shivamogga,2022,24.796006,12.8,37.0,1452.4,9.242424,1010.384298,0.019144
2,Karnataka,Shivamogga,2023,25.862466,13.0,39.3,751.4,11.691781,1011.566575,0.019144
3,Karnataka,Shivamogga,2024,25.993820,13.9,41.0,1359.0,10.768820,1010.710112,0.019144
4,Karnataka,Uttara Kannada,2015,27.601681,20.4,35.5,3006.5,NaN,NaN,0.008988

In [5]:
print(master.isnull().sum())

State               0
District            0
Year                0
Temperature         0
Min_Temperature     0
Max_Temperature     0
Rainfall            0
wspd               24
pres               34
Forest_Loss         0
dtype: int64

In [6]:
master = master.merge(
    elevation,
    on=["State", "District"],
    how="left"
)

print(master.shape)

master.head()

(78, 11)

,State,District,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation
0,Karnataka,Shivamogga,2021,24.506868,13.2,37.2,1779.7,8.926923,1010.807967,0.019144,677.877599
1,Karnataka,Shivamogga,2022,24.796006,12.8,37.0,1452.4,9.242424,1010.384298,0.019144,677.877599
2,Karnataka,Shivamogga,2023,25.862466,13.0,39.3,751.4,11.691781,1011.566575,0.019144,677.877599
3,Karnataka,Shivamogga,2024,25.993820,13.9,41.0,1359.0,10.768820,1010.710112,0.019144,677.877599
4,Karnataka,Uttara Kannada,2015,27.601681,20.4,35.5,3006.5,NaN,NaN,0.008988,429.982021

In [7]:
print(master.isnull().sum())

State               0
District            0
Year                0
Temperature         0
Min_Temperature     0
Max_Temperature     0
Rainfall            0
wspd               24
pres               34
Forest_Loss         0
Elevation           0
dtype: int64

In [8]:
master = master.merge(
    ndvi,
    on=["State", "District", "Year"],
    how="left"
)

print(master.shape)

master.head()

(78, 12)

,State,District,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation,NDVI
0,Karnataka,Shivamogga,2021,24.506868,13.2,37.2,1779.7,8.926923,1010.807967,0.019144,677.877599,0.586866
1,Karnataka,Shivamogga,2022,24.796006,12.8,37.0,1452.4,9.242424,1010.384298,0.019144,677.877599,0.586866
2,Karnataka,Shivamogga,2023,25.862466,13.0,39.3,751.4,11.691781,1011.566575,0.019144,677.877599,0.586866
3,Karnataka,Shivamogga,2024,25.993820,13.9,41.0,1359.0,10.768820,1010.710112,0.019144,677.877599,0.586866
4,Karnataka,Uttara Kannada,2015,27.601681,20.4,35.5,3006.5,NaN,NaN,0.008988,429.982021,0.586866

In [9]:
print("=" * 60)
print("MASTER DATASET")
print("=" * 60)

print("\nShape:")
print(master.shape)

print("\nColumns:")
print(master.columns.tolist())

print("\nMissing Values:")
print(master.isnull().sum())

print("\nDuplicate Rows:")
print(master.duplicated().sum())

print("\nData Types:")
print(master.dtypes)

============================================================
MASTER DATASET
============================================================

Shape:
(78, 12)

Columns:
['State', 'District', 'Year', 'Temperature', 'Min_Temperature', 'Max_Temperature', 'Rainfall', 'wspd', 'pres', 'Forest_Loss', 'Elevation', 'NDVI']

Missing Values:
State               0
District            0
Year                0
Temperature         0
Min_Temperature     0
Max_Temperature     0
Rainfall            0
wspd               24
pres               34
Forest_Loss         0
Elevation           0
NDVI                0
dtype: int64

Duplicate Rows:
0

Data Types:
State                  str
District               str
Year                 int64
Temperature        float64
Min_Temperature    float64
Max_Temperature    float64
Rainfall           float64
wspd               float64
pres               float64
Forest_Loss        float64
Elevation          float64
NDVI               float64
dtype: object

In [10]:
master.describe(include="all")

,State,District,Year,Temperature,Min_Temperature,Max_Temperature,Rainfall,wspd,pres,Forest_Loss,Elevation,NDVI
count,78,78,78.000000,78.000000,78.000000,78.000000,78.000000,54.000000,44.000000,78.000000,78.000000,7.800000e+01
unique,4,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Karnataka,Uttara Kannada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,28,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2019.807692,27.424320,18.296154,36.706410,2846.585897,10.236246,1010.218524,0.011157,372.259762,5.868660e-01
std,NaN,NaN,2.910160,1.817312,2.924036,1.750424,878.105244,2.621311,1.213591,0.006268,273.004381,1.408886e-16
min,NaN,NaN,2015.000000,20.748626,10.700000,31.800000,4.100000,5.897338,1008.741047,0.003779,71.222575,5.868660e-01
25%,NaN,NaN,2017.000000,27.527527,17.000000,36.050000,2317.575000,8.333329,1009.266038,0.004742,99.188848,5.868660e-01
50%,NaN,NaN,2020.000000,27.919543,18.100000,36.800000,2887.550000,9.943332,1009.976558,0.008988,211.357774,5.868660e-01
75%,NaN,NaN,2022.000000,28.402758,20.375000,37.175000,3298.850000,11.608699,1010.798410,0.016563,651.723530,5.868660e-01
max,NaN,NaN,2024.000000,30.150000,25.400000,42.100000,4865.300000,15.889863,1013.160274,0.021077,890.594716,5.868660e-01

In [11]:
master.to_csv(
    "../data/processed/master_environment_dataset.csv",
    index=False
)

print("Master Environmental Dataset Saved Successfully!")

Master Environmental Dataset Saved Successfully!